// Questions + meta data from eval framework
const input = [
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.FLOW_COVERAGE,
    questionType: QuestionType.DOUBLE,
    question: "FC1: What percentage of the VC lifecycle double can be implemented directly?",
    score: [
      new QuestionScore(Solution.MATTR, 0.6),
      new QuestionScore(Solution.TRINSIC, 0.4),
      new QuestionScore(Solution.VERAMO, 0.9),
      new QuestionScore(Solution.AZURE, 0.2),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.FLOW_COVERAGE,
    questionType: QuestionType.DOUBLE,
    question: "FC2: What percentage of the VC lifecycle is generally supported?",
    score: [
      new QuestionScore(Solution.MATTR, 0.9),
      new QuestionScore(Solution.TRINSIC, 0.9),
      new QuestionScore(Solution.VERAMO, 0.9),
      new QuestionScore(Solution.AZURE, 0.8),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.FLOW_COVERAGE,
    questionType: QuestionType.BOOL,
    question: "FC3: Can a wallet be built independently?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.FLOW_COVERAGE,
    questionType: QuestionType.ENUM,
    options: ["mobile", "cloud", "browser"],
    question: "FC4: What wallet/ storage options are supported?",
    score: [
      new QuestionScore(Solution.MATTR, 0.66),
      new QuestionScore(Solution.TRINSIC, 0.66),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0.66),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS1: Are ledger-based DID methods supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS2: Are non ledger-based DID methods supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS3: Are JSON-LD credentials supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS4: Are linked data proofs supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS5: Are BBS+ or CL signatures supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS6: Is there support for DIDComm?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS7: Is RevocationList2020 supported?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FUNCTIONALITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "FS8: Is there ODIC support?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.EXTENSIBILITY,
    questionType: QuestionType.BOOL,
    question: "FE1: Can the functionality be extended?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.EXTENSIBILITY,
    questionType: QuestionType.BOOL,
    question: "FE2: Can one contribute to the solution?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.DEPLOYMENT,
    questionType: QuestionType.ENUM,
    options: ["cloud", "mobile", "browser", "mixed"],
    question: "FD1: What deployment options are there?",
    score: [
      new QuestionScore(Solution.MATTR, 0.5),
      new QuestionScore(Solution.TRINSIC, 0.5),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0.5),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.DEPLOYMENT,
    questionType: QuestionType.BOOL,
    question: "FD2: Is there a quick deployment option?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.PLATFORM,
    questionType: QuestionType.BOOL,
    question: "FP1: Is there a REST API exposing all necessary functionality?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.FLEXIBILITY,
    criterionSubtype: CriterionSubtype.PLATFORM,
    questionType: QuestionType.BOOL,
    question: "FP2: Are multiple programming languages supported by the solution?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.SUPPORT,
    questionType: QuestionType.ENUM,
    options: ["tel", "mail", "chat", "forum"],
    question: "OS1: What support options are there?",
    score: [
      new QuestionScore(Solution.MATTR, 0.75),
      new QuestionScore(Solution.TRINSIC, 0.75),
      new QuestionScore(Solution.VERAMO, 0.25),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.SUPPORT,
    questionType: QuestionType.BOOL,
    question: "OS2: Is there a public issue tracker?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.DOCUMENTATION,
    questionType: QuestionType.DOUBLE,
    question: "OD1: What percentage of the implemented lifecycle functionality is described?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.DOCUMENTATION,
    questionType: QuestionType.BOOL,
    question: "OD2: Is there an API Documentation?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.DOCUMENTATION,
    questionType: QuestionType.BOOL,
    question: "OD3: Are there any code examples?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.MATURITY,
    questionType: QuestionType.BOOL,
    question: "OM1: Is there a release version?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.MATURITY,
    questionType: QuestionType.BOOL,
    question: "OM2: Are features not going to change?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.MATURITY,
    questionType: QuestionType.BOOL,
    question: "OM3: Is the solution older than a year?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "OT1: Are industry standards being used?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.STANDARS,
    questionType: QuestionType.BOOL,
    question: "OT2: Is interoperability proven by Plugfest?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.OVERHEAD,
    questionType: QuestionType.BOOL,
    question: "OO1: Are less than 100 LoCs needed for set up?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.OPERABILITY,
    criterionSubtype: CriterionSubtype.OVERHEAD,
    questionType: QuestionType.BOOL,
    question: "OO2: How many things have to be set up? (≤5)",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 0),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.DEPENDENCY,
    criterionSubtype: CriterionSubtype.KEYS,
    questionType: QuestionType.BOOL,
    question: "DK1: Is full control over private keys given?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.DEPENDENCY,
    criterionSubtype: CriterionSubtype.STACK,
    questionType: QuestionType.BOOL,
    question: "DS1: Can one own the whole tech stack?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.DEPENDENCY,
    criterionSubtype: CriterionSubtype.STACK,
    questionType: QuestionType.BOOL,
    question: "DS2: Is the still stack usable after the original developers are gone?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.DEPENDENCY,
    criterionSubtype: CriterionSubtype.COST,
    questionType: QuestionType.BOOL,
    question: "DC1: Is the solution free of charge?",
    score: [
      new QuestionScore(Solution.MATTR, 0),
      new QuestionScore(Solution.TRINSIC, 0),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 0),
    ],
  },
  {
    criterionType: CriterionType.DEPENDENCY,
    criterionSubtype: CriterionSubtype.COST,
    questionType: QuestionType.BOOL,
    question: "DC2: Is there a free developer plan?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.INVOLVEMENT,
    criterionSubtype: CriterionSubtype.COMMUNITY,
    questionType: QuestionType.BOOL,
    question: "IC1: Does the solution provider participate in community events?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.INVOLVEMENT,
    criterionSubtype: CriterionSubtype.COMMUNITY,
    questionType: QuestionType.BOOL,
    question: "IC2: Have they worked on open-source repositories?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.INVOLVEMENT,
    criterionSubtype: CriterionSubtype.COMMUNITY,
    questionType: QuestionType.BOOL,
    question: "IC3: Have they co-worked on SSI-related standards?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.INVOLVEMENT,
    criterionSubtype: CriterionSubtype.PRODUCT,
    questionType: QuestionType.BOOL,
    question: "IP1: Is the solution being worked on?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
  {
    criterionType: CriterionType.INVOLVEMENT,
    criterionSubtype: CriterionSubtype.PRODUCT,
    questionType: QuestionType.BOOL,
    question: "IP2: Is the solution leveraging open-source work?",
    score: [
      new QuestionScore(Solution.MATTR, 1),
      new QuestionScore(Solution.TRINSIC, 1),
      new QuestionScore(Solution.VERAMO, 1),
      new QuestionScore(Solution.AZURE, 1),
    ],
  },
];
